# Generated by Django 4.2.13 on 2026-05-17 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jams', '0002_jam_upgrade_jammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jam',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this JAM.', on_delete=django.db.models.deletion.CASCADE, related_name='created_jams', to=settings.AUTH_USER_MODEL),
        ),
    ]
