import pandas as pd
import os

def run_data_quality_checks(file_path):
    """
    Runs a set of data quality validation checks on a Parquet file.
    
    Args:
        file_path (str): Path to the Parquet file to validate.
    """
    print(f"🔍 Running Data Quality Checks on: {file_path}")
    
    if not os.path.exists(file_path):
        print(f"❌ Error: File {file_path} not found.")
        return False

    try:
        # Load the data
        df = pd.read_parquet(file_path)
        print(f"📊 Loaded {len(df)} rows for validation.")
        
        # --- RULE 1: Check for Nulls in Critical Columns ---
        # In a real scenario, we would define a list of mandatory columns
        critical_columns = ['region', 'species', 'catch_amount']
        for col in critical_matches := [c for c in critical_columns if c in df.columns]:
            null_count = df[col].isnull().sum()
            assert null_count == 0, f"❌ Rule Failed: Column '{col}' contains {null_count} null values."
            print(f"✅ Rule Passed: Column '{col}' has no nulls.")

        # --- RULE 2: Check for Negative Values in Numeric Columns ---
        if 'catch_amount' in df.columns:
            negative_count = (df['catch_amount'] < 0).sum()
            assert negative_count == 0, f"❌ Rule Failed: Found {negative_count} negative values in 'catch_amount'."
            print(f"✅ Rule Passed: No negative values in 'catch_amount'.")

        # --- RULE 3: Check for Duplicate Rows ---
        duplicate_count = df.duplicated().sum()
        assert duplicate_count == 0, f"❌ Rule Failed: Found {duplicate_count} duplicate rows."
        print(f"✅ Rule Passed: No duplicate rows found.")

        # --- RULE 4: Data Completeness (Minimum Row Count) ---
        assert len(df) > 0, "❌ Rule Failed: The dataset is empty."
        print(f"✅ Rule Passed: Dataset is not empty.")

        print("\n✨ ALL DATA QUALITY CHECKS PASSED SUCCESSFULLY! ✨")
        return True

    except AssertionError as e:
        print(f"\n❌ DATA QUALITY ALERT: {str(e)}")
        return False
    except Exception as e:
        print(f"❌ Unexpected error during DQ checks: {str(e)}")
        return False

if __name__ == "__main__":
    # Path to the processed parquet file generated by transform.py
    PROCESSED_FILE = "data-eng-project-team01/data/processed/sample.parquet"
    
    run_data_quality_checks(PROCESSED_FILE)